// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/[locale]" | "/[locale]/about" | "/[locale]/cases" | "/[locale]/cases/[slug]" | "/[locale]/contact" | "/[locale]/library" | "/[locale]/library/[slug]" | "/[locale]/notes" | "/[locale]/notes/[slug]" | "/[locale]/playbooks" | "/[locale]/playbooks/[slug]" | "/[locale]/privacy" | "/[locale]/products" | "/[locale]/products/[slug]" | "/[locale]/saas" | "/[locale]/terms" | "/[locale]/work-with-me" | "/admin" | "/admin/dashboard"
type AppRouteHandlerRoutes = "/api/admin/login" | "/api/admin/logout" | "/api/admin/notes" | "/api/notion-test" | "/api/sync-notes"
type PageRoutes = never
type LayoutRoutes = "/" | "/[locale]" | "/admin"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/[locale]": { "locale": string; }
  "/[locale]/about": { "locale": string; }
  "/[locale]/cases": { "locale": string; }
  "/[locale]/cases/[slug]": { "locale": string; "slug": string; }
  "/[locale]/contact": { "locale": string; }
  "/[locale]/library": { "locale": string; }
  "/[locale]/library/[slug]": { "locale": string; "slug": string; }
  "/[locale]/notes": { "locale": string; }
  "/[locale]/notes/[slug]": { "locale": string; "slug": string; }
  "/[locale]/playbooks": { "locale": string; }
  "/[locale]/playbooks/[slug]": { "locale": string; "slug": string; }
  "/[locale]/privacy": { "locale": string; }
  "/[locale]/products": { "locale": string; }
  "/[locale]/products/[slug]": { "locale": string; "slug": string; }
  "/[locale]/saas": { "locale": string; }
  "/[locale]/terms": { "locale": string; }
  "/[locale]/work-with-me": { "locale": string; }
  "/admin": {}
  "/admin/dashboard": {}
  "/api/admin/login": {}
  "/api/admin/logout": {}
  "/api/admin/notes": {}
  "/api/notion-test": {}
  "/api/sync-notes": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/[locale]": never
  "/admin": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
